server {
  listen 80 default_server;
  server_name _;

  location = /healthz {
    access_log off;
    return 200 "ok\n";
    add_header Content-Type text/plain;
  }

  location = / {
    default_type text/plain;
    return 200 "infra-macro-vps core gateway\n";
  }

  location /infisical/ {
    proxy_pass http://infisical:8080/;
  }

  location /couchdb/ {
    proxy_pass http://couchdb:5984/;
  }

  location /seaweed/master/ {
    proxy_pass http://seaweedfs:9333/;
  }

  location /seaweed/filer/ {
    proxy_pass http://seaweedfs:8888/;
  }

  location /seaweed/s3/ {
    proxy_pass http://seaweedfs:8333/;
  }
}
