name: test-infisical-oidc-official

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Pull secrets from Infisical via OIDC
        uses: Infisical/secrets-action@v1.0.10
        with:
          method: "oidc"
          identity-id: "0a100e5d-1422-437e-b447-e032f32403fa"
          project-slug: "victus-main-server-qy-2z"
          env-slug: "production"

      - name: Verify action ran
        run: |
          echo "Infisical action finished"
